export const countriesData = [
  // Switzerland - Multiple languages
  {
    code: 'CH',
    name: 'Switzerland',
    lang: 'en',
    nativeName: 'Switzerland',
    isActive: true,
  },
  {
    code: 'CH',
    name: 'Suisse',
    lang: 'fr',
    nativeName: 'Suisse',
    isActive: true,
  },
  {
    code: 'CH',
    name: 'Schweiz',
    lang: 'de',
    nativeName: 'Schweiz',
    isActive: true,
  },
  {
    code: 'CH',
    name: 'Svizzera',
    lang: 'it',
    nativeName: 'Svizzera',
    isActive: true,
  },
  {
    code: 'CH',
    name: 'Zvicra',
    lang: 'sq',
    nativeName: 'Zvicër',
    isActive: true,
  },
  {
    code: 'CH',
    name: 'Suiza',
    lang: 'es',
    nativeName: 'Schweiz',
    isActive: true,
  },

  // France
  {
    code: 'FR',
    name: 'France',
    lang: 'en',
    nativeName: 'France',
    isActive: true,
  },
  {
    code: 'FR',
    name: 'France',
    lang: 'fr',
    nativeName: 'France',
    isActive: true,
  },
  {
    code: 'FR',
    name: 'Frankreich',
    lang: 'de',
    nativeName: 'France',
    isActive: true,
  },
  {
    code: 'FR',
    name: 'Francia',
    lang: 'it',
    nativeName: 'France',
    isActive: true,
  },
  {
    code: 'FR',
    name: 'Franca',
    lang: 'sq',
    nativeName: 'France',
    isActive: true,
  },
  {
    code: 'FR',
    name: 'Francia',
    lang: 'es',
    nativeName: 'France',
    isActive: true,
  },

  // United Kingdom
  {
    code: 'GB',
    name: 'United Kingdom',
    lang: 'en',
    nativeName: 'United Kingdom',
    isActive: true,
  },
  {
    code: 'GB',
    name: 'Royaume-Uni',
    lang: 'fr',
    nativeName: 'United Kingdom',
    isActive: true,
  },
  {
    code: 'GB',
    name: 'Vereinigtes Königreich',
    lang: 'de',
    nativeName: 'United Kingdom',
    isActive: true,
  },
  {
    code: 'GB',
    name: 'Regno Unito',
    lang: 'it',
    nativeName: 'United Kingdom',
    isActive: true,
  },
  {
    code: 'GB',
    name: 'Mbretëria e Bashkuar',
    lang: 'sq',
    nativeName: 'United Kingdom',
    isActive: true,
  },
  {
    code: 'GB',
    name: 'Reino Unido',
    lang: 'es',
    nativeName: 'United Kingdom',
    isActive: true,
  },

  // Kosovo
  {
    code: 'XK',
    name: 'Kosovo',
    lang: 'en',
    nativeName: 'Kosova',
    isActive: true,
  },
  {
    code: 'XK',
    name: 'Kosovo',
    lang: 'fr',
    nativeName: 'Kosova',
    isActive: true,
  },
  {
    code: 'XK',
    name: 'Kosovo',
    lang: 'de',
    nativeName: 'Kosova',
    isActive: true,
  },
  {
    code: 'XK',
    name: 'Kosovo',
    lang: 'it',
    nativeName: 'Kosova',
    isActive: true,
  },
  {
    code: 'XK',
    name: 'Kosovë',
    lang: 'sq',
    nativeName: 'Kosova',
    isActive: true,
  },
  {
    code: 'XK',
    name: 'Kosovo',
    lang: 'es',
    nativeName: 'Kosova',
    isActive: true,
  },

  // Albania
  {
    code: 'AL',
    name: 'Albania',
    lang: 'en',
    nativeName: 'Shqipëri',
    isActive: true,
  },
  {
    code: 'AL',
    name: 'Albanie',
    lang: 'fr',
    nativeName: 'Shqipëri',
    isActive: true,
  },
  {
    code: 'AL',
    name: 'Albanien',
    lang: 'de',
    nativeName: 'Shqipëri',
    isActive: true,
  },
  {
    code: 'AL',
    name: 'Albania',
    lang: 'it',
    nativeName: 'Shqipëri',
    isActive: true,
  },
  {
    code: 'AL',
    name: 'Shqipëri',
    lang: 'sq',
    nativeName: 'Shqipëri',
    isActive: true,
  },
  {
    code: 'AL',
    name: 'Albania',
    lang: 'es',
    nativeName: 'Shqipëri',
    isActive: true,
  },

  // Austria
  {
    code: 'AT',
    name: 'Austria',
    lang: 'en',
    nativeName: 'Österreich',
    isActive: true,
  },
  {
    code: 'AT',
    name: 'Autriche',
    lang: 'fr',
    nativeName: 'Österreich',
    isActive: true,
  },
  {
    code: 'AT',
    name: 'Österreich',
    lang: 'de',
    nativeName: 'Österreich',
    isActive: true,
  },
  {
    code: 'AT',
    name: 'Austria',
    lang: 'it',
    nativeName: 'Österreich',
    isActive: true,
  },
  {
    code: 'AT',
    name: 'Austri',
    lang: 'sq',
    nativeName: 'Österreich',
    isActive: true,
  },
  {
    code: 'AT',
    name: 'Austria',
    lang: 'es',
    nativeName: 'Österreich',
    isActive: true,
  },

  // Germany
  {
    code: 'DE',
    name: 'Germany',
    lang: 'en',
    nativeName: 'Deutschland',
    isActive: true,
  },
  {
    code: 'DE',
    name: 'Allemagne',
    lang: 'fr',
    nativeName: 'Deutschland',
    isActive: true,
  },
  {
    code: 'DE',
    name: 'Deutschland',
    lang: 'de',
    nativeName: 'Deutschland',
    isActive: true,
  },
  {
    code: 'DE',
    name: 'Germania',
    lang: 'it',
    nativeName: 'Deutschland',
    isActive: true,
  },
  {
    code: 'DE',
    name: 'Gjermani',
    lang: 'sq',
    nativeName: 'Deutschland',
    isActive: true,
  },
  {
    code: 'DE',
    name: 'Alemania',
    lang: 'es',
    nativeName: 'Deutschland',
    isActive: true,
  },
  // Spain multiple languages
  {
    code: 'ES',
    name: 'Spain',
    lang: 'en',
    nativeName: 'España',
    isActive: true,
  },
  {
    code: 'ES',
    name: 'Espagne',
    lang: 'fr',
    nativeName: 'España',
    isActive: true,
  },
  {
    code: 'ES',
    name: 'Spanien',
    lang: 'de',
    nativeName: 'España',
    isActive: true,
  },
  {
    code: 'ES',
    name: 'Spagna',
    lang: 'it',
    nativeName: 'España',
    isActive: true,
  },
  {
    code: 'ES',
    name: 'Spanja',
    lang: 'sq',
    nativeName: 'España',
    isActive: true,
  },
  {
    code: 'ES',
    name: 'España',
    lang: 'es',
    nativeName: 'España',
    isActive: true,
  },
  // Italy multiple languages
  {
    code: 'IT',
    name: 'Italy',
    lang: 'en',
    nativeName: 'Italia',
    isActive: true,
  },
  {
    code: 'IT',
    name: 'Italie',
    lang: 'fr',
    nativeName: 'Italia',
    isActive: true,
  },
  {
    code: 'IT',
    name: 'Italien',
    lang: 'de',
    nativeName: 'Italia',
    isActive: true,
  },
  {
    code: 'IT',
    name: 'Italia',
    lang: 'it',
    nativeName: 'Italia',
    isActive: true,
  },
  {
    code: 'IT',
    name: 'Italia',
    lang: 'sq',
    nativeName: 'Italia',
    isActive: true,
  },
  {
    code: 'IT',
    name: 'Italia',
    lang: 'es',
    nativeName: 'Italia',
    isActive: true,
  },
];
