export const countriesData = [
  // Switzerland - Multiple languages
  {
    code: 'CH',
    name: 'Switzerland',
    lang: 'en',
    nativeName: 'Switzerland',
    phoneCode: '+41',
    flag: '🇨🇭',
    isActive: true,
  },
  {
    code: 'CH',
    name: 'Suisse',
    lang: 'fr',
    nativeName: 'Suisse',
    phoneCode: '+41',
    flag: '🇨🇭',
    isActive: true,
  },
  {
    code: 'CH',
    name: 'Schweiz',
    lang: 'de',
    nativeName: 'Schweiz',
    phoneCode: '+41',
    flag: '🇨🇭',
    isActive: true,
  },
  {
    code: 'CH',
    name: 'Svizzera',
    lang: 'it',
    nativeName: 'Svizzera',
    phoneCode: '+41',
    flag: '🇨🇭',
    isActive: true,
  },
  {
    code: 'CH',
    name: 'Zvicra',
    lang: 'sq',
    nativeName: 'Zvicër',
    phoneCode: '+41',
    flag: '🇨🇭',
    isActive: true,
  },
  {
    code: 'CH',
    name: 'Suiza',
    lang: 'es',
    nativeName: 'Schweiz',
    phoneCode: '+41',
    flag: '🇨🇭',
    isActive: true,
  },

  // France
  {
    code: 'FR',
    name: 'France',
    lang: 'en',
    nativeName: 'France',
    phoneCode: '+33',
    flag: '🇫🇷',
    isActive: true,
  },
  {
    code: 'FR',
    name: 'France',
    lang: 'fr',
    nativeName: 'France',
    phoneCode: '+33',
    flag: '🇫🇷',
    isActive: true,
  },
  {
    code: 'FR',
    name: 'Frankreich',
    lang: 'de',
    nativeName: 'France',
    phoneCode: '+33',
    flag: '🇫🇷',
    isActive: true,
  },
  {
    code: 'FR',
    name: 'Francia',
    lang: 'it',
    nativeName: 'France',
    phoneCode: '+33',
    flag: '🇫🇷',
    isActive: true,
  },
  {
    code: 'FR',
    name: 'Franca',
    lang: 'sq',
    nativeName: 'France',
    phoneCode: '+33',
    flag: '🇫🇷',
    isActive: true,
  },
  {
    code: 'FR',
    name: 'Francia',
    lang: 'es',
    nativeName: 'France',
    phoneCode: '+33',
    flag: '🇫🇷',
    isActive: true,
  },

  // United Kingdom
  {
    code: 'GB',
    name: 'United Kingdom',
    lang: 'en',
    nativeName: 'United Kingdom',
    phoneCode: '+44',
    flag: '🇬🇧',
    isActive: true,
  },
  {
    code: 'GB',
    name: 'Royaume-Uni',
    lang: 'fr',
    nativeName: 'United Kingdom',
    phoneCode: '+44',
    flag: '🇬🇧',
    isActive: true,
  },
  {
    code: 'GB',
    name: 'Vereinigtes Königreich',
    lang: 'de',
    nativeName: 'United Kingdom',
    phoneCode: '+44',
    flag: '🇬🇧',
    isActive: true,
  },
  {
    code: 'GB',
    name: 'Regno Unito',
    lang: 'it',
    nativeName: 'United Kingdom',
    phoneCode: '+44',
    flag: '🇬🇧',
    isActive: true,
  },
  {
    code: 'GB',
    name: 'Mbretëria e Bashkuar',
    lang: 'sq',
    nativeName: 'United Kingdom',
    phoneCode: '+44',
    flag: '🇬🇧',
    isActive: true,
  },
  {
    code: 'GB',
    name: 'Reino Unido',
    lang: 'es',
    nativeName: 'United Kingdom',
    phoneCode: '+44',
    flag: '🇬🇧',
    isActive: true,
  },

  // Kosovo
  {
    code: 'XK',
    name: 'Kosovo',
    lang: 'en',
    nativeName: 'Kosova',
    phoneCode: '+383',
    flag: '🇽🇰',
    isActive: true,
  },
  {
    code: 'XK',
    name: 'Kosovo',
    lang: 'fr',
    nativeName: 'Kosova',
    phoneCode: '+383',
    flag: '🇽🇰',
    isActive: true,
  },
  {
    code: 'XK',
    name: 'Kosovo',
    lang: 'de',
    nativeName: 'Kosova',
    phoneCode: '+383',
    flag: '🇽🇰',
    isActive: true,
  },
  {
    code: 'XK',
    name: 'Kosovo',
    lang: 'it',
    nativeName: 'Kosova',
    phoneCode: '+383',
    flag: '🇽🇰',
    isActive: true,
  },
  {
    code: 'XK',
    name: 'Kosovë',
    lang: 'sq',
    nativeName: 'Kosova',
    phoneCode: '+383',
    flag: '🇽🇰',
    isActive: true,
  },
  {
    code: 'XK',
    name: 'Kosovo',
    lang: 'es',
    nativeName: 'Kosova',
    phoneCode: '+383',
    flag: '🇽🇰',
    isActive: true,
  },

  // Albania
  {
    code: 'AL',
    name: 'Albania',
    lang: 'en',
    nativeName: 'Shqipëri',
    phoneCode: '+355',
    flag: '🇦🇱',
    isActive: true,
  },
  {
    code: 'AL',
    name: 'Albanie',
    lang: 'fr',
    nativeName: 'Shqipëri',
    phoneCode: '+355',
    flag: '🇦🇱',
    isActive: true,
  },
  {
    code: 'AL',
    name: 'Albanien',
    lang: 'de',
    nativeName: 'Shqipëri',
    phoneCode: '+355',
    flag: '🇦🇱',
    isActive: true,
  },
  {
    code: 'AL',
    name: 'Albania',
    lang: 'it',
    nativeName: 'Shqipëri',
    phoneCode: '+355',
    flag: '🇦🇱',
    isActive: true,
  },
  {
    code: 'AL',
    name: 'Shqipëri',
    lang: 'sq',
    nativeName: 'Shqipëri',
    phoneCode: '+355',
    flag: '🇦🇱',
    isActive: true,
  },
  {
    code: 'AL',
    name: 'Albania',
    lang: 'es',
    nativeName: 'Shqipëri',
    phoneCode: '+355',
    flag: '🇦🇱',
    isActive: true,
  },

  // Austria
  {
    code: 'AT',
    name: 'Austria',
    lang: 'en',
    nativeName: 'Österreich',
    phoneCode: '+43',
    flag: '🇦🇹',
    isActive: true,
  },
  {
    code: 'AT',
    name: 'Autriche',
    lang: 'fr',
    nativeName: 'Österreich',
    phoneCode: '+43',
    flag: '🇦🇹',
    isActive: true,
  },
  {
    code: 'AT',
    name: 'Österreich',
    lang: 'de',
    nativeName: 'Österreich',
    phoneCode: '+43',
    flag: '🇦🇹',
    isActive: true,
  },
  {
    code: 'AT',
    name: 'Austria',
    lang: 'it',
    nativeName: 'Österreich',
    phoneCode: '+43',
    flag: '🇦🇹',
    isActive: true,
  },
  {
    code: 'AT',
    name: 'Austri',
    lang: 'sq',
    nativeName: 'Österreich',
    phoneCode: '+43',
    flag: '🇦🇹',
    isActive: true,
  },
  {
    code: 'AT',
    name: 'Austria',
    lang: 'es',
    nativeName: 'Österreich',
    phoneCode: '+43',
    flag: '🇦🇹',
    isActive: true,
  },

  // Germany
  {
    code: 'DE',
    name: 'Germany',
    lang: 'en',
    nativeName: 'Deutschland',
    phoneCode: '+49',
    flag: '🇩🇪',
    isActive: true,
  },
  {
    code: 'DE',
    name: 'Allemagne',
    lang: 'fr',
    nativeName: 'Deutschland',
    phoneCode: '+49',
    flag: '🇩🇪',
    isActive: true,
  },
  {
    code: 'DE',
    name: 'Deutschland',
    lang: 'de',
    nativeName: 'Deutschland',
    phoneCode: '+49',
    flag: '🇩🇪',
    isActive: true,
  },
  {
    code: 'DE',
    name: 'Germania',
    lang: 'it',
    nativeName: 'Deutschland',
    phoneCode: '+49',
    flag: '🇩🇪',
    isActive: true,
  },
  {
    code: 'DE',
    name: 'Gjermani',
    lang: 'sq',
    nativeName: 'Deutschland',
    phoneCode: '+49',
    flag: '🇩🇪',
    isActive: true,
  },
  {
    code: 'DE',
    name: 'Alemania',
    lang: 'es',
    nativeName: 'Deutschland',
    phoneCode: '+49',
    flag: '🇩🇪',
    isActive: true,
  },
  // Spain multiple languages
  {
    code: 'ES',
    name: 'Spain',
    lang: 'en',
    nativeName: 'España',
    phoneCode: '+34',
    flag: '🇪🇸',
    isActive: true,
  },
  {
    code: 'ES',
    name: 'Espagne',
    lang: 'fr',
    nativeName: 'España',
    phoneCode: '+34',
    flag: '🇪🇸',
    isActive: true,
  },
  {
    code: 'ES',
    name: 'Spanien',
    lang: 'de',
    nativeName: 'España',
    phoneCode: '+34',
    flag: '🇪🇸',
    isActive: true,
  },
  {
    code: 'ES',
    name: 'Spagna',
    lang: 'it',
    nativeName: 'España',
    phoneCode: '+34',
    flag: '🇪🇸',
    isActive: true,
  },
  {
    code: 'ES',
    name: 'Spanja',
    lang: 'sq',
    nativeName: 'España',
    phoneCode: '+34',
    flag: '🇪🇸',
    isActive: true,
  },
  {
    code: 'ES',
    name: 'España',
    lang: 'es',
    nativeName: 'España',
    phoneCode: '+34',
    flag: '🇪🇸',
    isActive: true,
  },
  // Italy multiple languages
  {
    code: 'IT',
    name: 'Italy',
    lang: 'en',
    nativeName: 'Italia',
    phoneCode: '+39',
    flag: '🇮🇹',
    isActive: true,
  },
  {
    code: 'IT',
    name: 'Italie',
    lang: 'fr',
    nativeName: 'Italia',
    phoneCode: '+39',
    flag: '🇮🇹',
    isActive: true,
  },
  {
    code: 'IT',
    name: 'Italien',
    lang: 'de',
    nativeName: 'Italia',
    phoneCode: '+39',
    flag: '🇮🇹',
    isActive: true,
  },
  {
    code: 'IT',
    name: 'Italia',
    lang: 'it',
    nativeName: 'Italia',
    phoneCode: '+39',
    flag: '🇮🇹',
    isActive: true,
  },
  {
    code: 'IT',
    name: 'Italia',
    lang: 'sq',
    nativeName: 'Italia',
    phoneCode: '+39',
    flag: '🇮🇹',
    isActive: true,
  },
  {
    code: 'IT',
    name: 'Italia',
    lang: 'es',
    nativeName: 'Italia',
    phoneCode: '+39',
    flag: '🇮🇹',
    isActive: true,
  },
];
