export const serviceCategoriesData = [
  // Haircut / Coiffure
  {
    code: 'haircut',
    name: 'Haircut',
    lang: 'en',
    description: 'Hair cutting and styling services',
    icon: '✂️',
    sortOrder: 1,
    isActive: true,
  },
  {
    code: 'haircut',
    name: 'Coupe de cheveux',
    lang: 'fr',
    description: 'Services de coupe et de coiffure',
    icon: '✂️',
    sortOrder: 1,
    isActive: true,
  },
  {
    code: 'haircut',
    name: 'Haarschnitt',
    lang: 'de',
    description: 'Haarschnitt- und Styling-Dienstleistungen',
    icon: '✂️',
    sortOrder: 1,
    isActive: true,
  },
  {
    code: 'haircut',
    name: 'Taglio di capelli',
    lang: 'it',
    description: 'Servizi di taglio e acconciatura',
    icon: '✂️',
    sortOrder: 1,
    isActive: true,
  },
  {
    code: 'haircut',
    name: 'Corte de pelo',
    lang: 'es',
    description: 'Servicios de corte y peinado',
    icon: '✂️',
    sortOrder: 1,
    isActive: true,
  },
  {
    code: 'haircut',
    name: 'Prerje flokësh',
    lang: 'sq',
    description: 'Shërbime për prerje dhe stilim flokësh',
    icon: '✂️',
    sortOrder: 1,
    isActive: true,
  },

  // Coloring
  {
    code: 'coloring',
    name: 'Coloring',
    lang: 'en',
    description: 'Hair coloring and highlighting services',
    icon: '🎨',
    sortOrder: 2,
    isActive: true,
  },
  {
    code: 'coloring',
    name: 'Coloration',
    lang: 'fr',
    description: 'Services de coloration et de mèches',
    icon: '🎨',
    sortOrder: 2,
    isActive: true,
  },
  {
    code: 'coloring',
    name: 'Färbung',
    lang: 'de',
    description: 'Haarfärbe- und Highlight-Services',
    icon: '🎨',
    sortOrder: 2,
    isActive: true,
  },
  {
    code: 'coloring',
    name: 'Colorazione',
    lang: 'it',
    description: 'Servizi di colorazione e colpi di sole',
    icon: '🎨',
    sortOrder: 2,
    isActive: true,
  },
  {
    code: 'coloring',
    name: 'Coloración',
    lang: 'es',
    description: 'Servicios de coloración e iluminación',
    icon: '🎨',
    sortOrder: 2,
    isActive: true,
  },
  {
    code: 'coloring',
    name: 'Ngjyrosje',
    lang: 'sq',
    description: 'Shërbime për ngjyrosje dhe theksim flokësh',
    icon: '🎨',
    sortOrder: 2,
    isActive: true,
  },

  // Styling
  {
    code: 'styling',
    name: 'Styling',
    lang: 'en',
    description: 'Hair styling and treatment services',
    icon: '💇',
    sortOrder: 3,
    isActive: true,
  },
  {
    code: 'styling',
    name: 'Coiffage',
    lang: 'fr',
    description: 'Services de coiffure et de soins',
    icon: '💇',
    sortOrder: 3,
    isActive: true,
  },
  {
    code: 'styling',
    name: 'Styling',
    lang: 'de',
    description: 'Haarstyling- und Behandlungsservices',
    icon: '💇',
    sortOrder: 3,
    isActive: true,
  },
  {
    code: 'styling',
    name: 'Acconciatura',
    lang: 'it',
    description: 'Servizi di acconciatura e trattamento',
    icon: '💇',
    sortOrder: 3,
    isActive: true,
  },
  {
    code: 'styling',
    name: 'Peinado',
    lang: 'es',
    description: 'Servicios de peinado y tratamiento',
    icon: '💇',
    sortOrder: 3,
    isActive: true,
  },
  {
    code: 'styling',
    name: 'Stilim',
    lang: 'sq',
    description: 'Shërbime për stilim dhe trajtim flokësh',
    icon: '💇',
    sortOrder: 3,
    isActive: true,
  },

  // Manicure
  {
    code: 'manicure',
    name: 'Manicure',
    lang: 'en',
    description: 'Hand and nail care services',
    icon: '💅',
    sortOrder: 4,
    isActive: true,
  },
  {
    code: 'manicure',
    name: 'Manucure',
    lang: 'fr',
    description: 'Soins des mains et des ongles',
    icon: '💅',
    sortOrder: 4,
    isActive: true,
  },
  {
    code: 'manicure',
    name: 'Maniküre',
    lang: 'de',
    description: 'Hand- und Nagelpflege',
    icon: '💅',
    sortOrder: 4,
    isActive: true,
  },
  {
    code: 'manicure',
    name: 'Manicure',
    lang: 'it',
    description: 'Servizi di cura delle mani e delle unghie',
    icon: '💅',
    sortOrder: 4,
    isActive: true,
  },
  {
    code: 'manicure',
    name: 'Manicura',
    lang: 'es',
    description: 'Servicios de cuidado de manos y uñas',
    icon: '💅',
    sortOrder: 4,
    isActive: true,
  },
  {
    code: 'manicure',
    name: 'Manikyr',
    lang: 'sq',
    description: 'Shërbime për kujdesin e duarve dhe thonjve',
    icon: '💅',
    sortOrder: 4,
    isActive: true,
  },

  // Pedicure
  {
    code: 'pedicure',
    name: 'Pedicure',
    lang: 'en',
    description: 'Foot and nail care services',
    icon: '🦶',
    sortOrder: 5,
    isActive: true,
  },
  {
    code: 'pedicure',
    name: 'Pédicure',
    lang: 'fr',
    description: 'Soins des pieds et des ongles',
    icon: '🦶',
    sortOrder: 5,
    isActive: true,
  },
  {
    code: 'pedicure',
    name: 'Pediküre',
    lang: 'de',
    description: 'Fuß- und Nagelpflege',
    icon: '🦶',
    sortOrder: 5,
    isActive: true,
  },
  {
    code: 'pedicure',
    name: 'Pedicure',
    lang: 'it',
    description: 'Servizi di cura dei piedi e delle unghie',
    icon: '🦶',
    sortOrder: 5,
    isActive: true,
  },
  {
    code: 'pedicure',
    name: 'Pedicura',
    lang: 'es',
    description: 'Servicios de cuidado de pies y uñas',
    icon: '🦶',
    sortOrder: 5,
    isActive: true,
  },
  {
    code: 'pedicure',
    name: 'Pedikyr',
    lang: 'sq',
    description: 'Shërbime për kujdesin e këmbëve dhe thonjve',
    icon: '🦶',
    sortOrder: 5,
    isActive: true,
  },

  // Facial
  {
    code: 'facial',
    name: 'Facial',
    lang: 'en',
    description: 'Facial care and treatment services',
    icon: '🧖',
    sortOrder: 6,
    isActive: true,
  },
  {
    code: 'facial',
    name: 'Soin du visage',
    lang: 'fr',
    description: 'Soins et traitements du visage',
    icon: '🧖',
    sortOrder: 6,
    isActive: true,
  },
  {
    code: 'facial',
    name: 'Gesichtsbehandlung',
    lang: 'de',
    description: 'Gesichtspflege und Behandlungen',
    icon: '🧖',
    sortOrder: 6,
    isActive: true,
  },
  {
    code: 'facial',
    name: 'Trattamento viso',
    lang: 'it',
    description: 'Servizi di cura e trattamento del viso',
    icon: '🧖',
    sortOrder: 6,
    isActive: true,
  },
  {
    code: 'facial',
    name: 'Facial',
    lang: 'es',
    description: 'Servicios de cuidado y tratamiento facial',
    icon: '🧖',
    sortOrder: 6,
    isActive: true,
  },
  {
    code: 'facial',
    name: 'Trajtim fytyre',
    lang: 'sq',
    description: 'Shërbime për kujdesin dhe trajtimin e fytyrës',
    icon: '🧖',
    sortOrder: 6,
    isActive: true,
  },

  // Massage
  {
    code: 'massage',
    name: 'Massage',
    lang: 'en',
    description: 'Therapeutic massage services',
    icon: '💆',
    sortOrder: 7,
    isActive: true,
  },
  {
    code: 'massage',
    name: 'Massage',
    lang: 'fr',
    description: 'Services de massage thérapeutique',
    icon: '💆',
    sortOrder: 7,
    isActive: true,
  },
  {
    code: 'massage',
    name: 'Massage',
    lang: 'de',
    description: 'Therapeutische Massage-Services',
    icon: '💆',
    sortOrder: 7,
    isActive: true,
  },
  {
    code: 'massage',
    name: 'Massaggio',
    lang: 'it',
    description: 'Servizi di massaggio terapeutico',
    icon: '💆',
    sortOrder: 7,
    isActive: true,
  },
  {
    code: 'massage',
    name: 'Masaje',
    lang: 'es',
    description: 'Servicios de masaje terapéutico',
    icon: '💆',
    sortOrder: 7,
    isActive: true,
  },
  {
    code: 'massage',
    name: 'Masazh',
    lang: 'sq',
    description: 'Shërbime masazhi terapeutik',
    icon: '💆',
    sortOrder: 7,
    isActive: true,
  },

  // Makeup
  {
    code: 'makeup',
    name: 'Makeup',
    lang: 'en',
    description: 'Professional makeup services',
    icon: '💄',
    sortOrder: 8,
    isActive: true,
  },
  {
    code: 'makeup',
    name: 'Maquillage',
    lang: 'fr',
    description: 'Services de maquillage professionnel',
    icon: '💄',
    sortOrder: 8,
    isActive: true,
  },
  {
    code: 'makeup',
    name: 'Make-up',
    lang: 'de',
    description: 'Professionelle Make-up-Services',
    icon: '💄',
    sortOrder: 8,
    isActive: true,
  },
  {
    code: 'makeup',
    name: 'Trucco',
    lang: 'it',
    description: 'Servizi di trucco professionale',
    icon: '💄',
    sortOrder: 8,
    isActive: true,
  },
  {
    code: 'makeup',
    name: 'Maquillaje',
    lang: 'es',
    description: 'Servicios de maquillaje profesional',
    icon: '💄',
    sortOrder: 8,
    isActive: true,
  },
  {
    code: 'makeup',
    name: 'Grimi',
    lang: 'sq',
    description: 'Shërbime profesionale grimi',
    icon: '💄',
    sortOrder: 8,
    isActive: true,
  },

  // Waxing
  {
    code: 'waxing',
    name: 'Waxing',
    lang: 'en',
    description: 'Hair removal waxing services',
    icon: '🪒',
    sortOrder: 9,
    isActive: true,
  },
  {
    code: 'waxing',
    name: 'Épilation',
    lang: 'fr',
    description: "Services d'épilation à la cire",
    icon: '🪒',
    sortOrder: 9,
    isActive: true,
  },
  {
    code: 'waxing',
    name: 'Waxing',
    lang: 'de',
    description: 'Haarentfernung durch Waxing',
    icon: '🪒',
    sortOrder: 9,
    isActive: true,
  },
  {
    code: 'waxing',
    name: 'Ceretta',
    lang: 'it',
    description: 'Servizi di depilazione con ceretta',
    icon: '🪒',
    sortOrder: 9,
    isActive: true,
  },
  {
    code: 'waxing',
    name: 'Depilación',
    lang: 'es',
    description: 'Servicios de depilación con cera',
    icon: '🪒',
    sortOrder: 9,
    isActive: true,
  },
  {
    code: 'waxing',
    name: 'Depilim me dyllë',
    lang: 'sq',
    description: 'Shërbime depilimi me dyllë',
    icon: '🪒',
    sortOrder: 9,
    isActive: true,
  },

  // Barbering
  {
    code: 'barbering',
    name: 'Barbering',
    lang: 'en',
    description: 'Traditional barber services',
    icon: '💈',
    sortOrder: 10,
    isActive: true,
  },
  {
    code: 'barbering',
    name: 'Barbier',
    lang: 'fr',
    description: 'Services de barbier traditionnels',
    icon: '💈',
    sortOrder: 10,
    isActive: true,
  },
  {
    code: 'barbering',
    name: 'Barbier',
    lang: 'de',
    description: 'Traditionelle Barbier-Services',
    icon: '💈',
    sortOrder: 10,
    isActive: true,
  },
  {
    code: 'barbering',
    name: 'Barberia',
    lang: 'it',
    description: 'Servizi da barbiere tradizionale',
    icon: '💈',
    sortOrder: 10,
    isActive: true,
  },
  {
    code: 'barbering',
    name: 'Barbería',
    lang: 'es',
    description: 'Servicios de barbería tradicional',
    icon: '💈',
    sortOrder: 10,
    isActive: true,
  },
  {
    code: 'barbering',
    name: 'Berber',
    lang: 'sq',
    description: 'Shërbime tradicionale berberi',
    icon: '💈',
    sortOrder: 10,
    isActive: true,
  },

  // Other
  {
    code: 'other',
    name: 'Other',
    lang: 'en',
    description: 'Other beauty and wellness services',
    icon: '✨',
    sortOrder: 99,
    isActive: true,
  },
  {
    code: 'other',
    name: 'Autre',
    lang: 'fr',
    description: 'Autres services de beauté et bien-être',
    icon: '✨',
    sortOrder: 99,
    isActive: true,
  },
  {
    code: 'other',
    name: 'Sonstige',
    lang: 'de',
    description: 'Andere Schönheits- und Wellness-Services',
    icon: '✨',
    sortOrder: 99,
    isActive: true,
  },
  {
    code: 'other',
    name: 'Altro',
    lang: 'it',
    description: 'Altri servizi di bellezza e benessere',
    icon: '✨',
    sortOrder: 99,
    isActive: true,
  },
  {
    code: 'other',
    name: 'Otro',
    lang: 'es',
    description: 'Otros servicios de belleza y bienestar',
    icon: '✨',
    sortOrder: 99,
    isActive: true,
  },
  {
    code: 'other',
    name: 'Të tjera',
    lang: 'sq',
    description: 'Shërbime të tjera bukurie dhe mirëqenie',
    icon: '✨',
    sortOrder: 99,
    isActive: true,
  },
];
