import { ServiceCategory } from 'src/service-categories/entities/service-category.entity';

export const serviceCategoriesData: Partial<ServiceCategory>[] = [
  {
    code: 'haircut',
    name: 'Haircut',
    translations: { en: 'Haircut', fr: 'Coupe de cheveux', de: 'Haarschnitt', it: 'Taglio di capelli', sq: 'Prerje flokësh', es: 'Corte de pelo' },
    description: 'Hair cutting and styling services',
    descriptionTranslations: { en: 'Hair cutting and styling services', fr: 'Services de coupe et de coiffure', de: 'Haarschnitt- und Styling-Dienstleistungen', it: 'Servizi di taglio e acconciatura', sq: 'Shërbime për prerje dhe stilim flokësh', es: 'Servicios de corte y peinado' },
    icon: '✂️',
    sortOrder: 1,
    isActive: true,
  },
  {
    code: 'coloring',
    name: 'Coloring',
    translations: { en: 'Coloring', fr: 'Coloration', de: 'Färbung', it: 'Colorazione', sq: 'Ngjyrosje', es: 'Coloración' },
    description: 'Hair coloring and highlighting services',
    descriptionTranslations: { en: 'Hair coloring and highlighting services', fr: 'Services de coloration et de mèches', de: 'Haarfärbe- und Highlight-Services', it: 'Servizi di colorazione e colpi di sole', sq: 'Shërbime për ngjyrosje dhe theksim flokësh', es: 'Servicios de coloración e iluminación' },
    icon: '🎨',
    sortOrder: 2,
    isActive: true,
  },
  {
    code: 'styling',
    name: 'Styling',
    translations: { en: 'Styling', fr: 'Coiffage', de: 'Styling', it: 'Acconciatura', sq: 'Stilim', es: 'Peinado' },
    description: 'Hair styling and treatment services',
    descriptionTranslations: { en: 'Hair styling and treatment services', fr: 'Services de coiffure et de soins', de: 'Haarstyling- und Behandlungsservices', it: 'Servizi di acconciatura e trattamento', sq: 'Shërbime për stilim dhe trajtim flokësh', es: 'Servicios de peinado y tratamiento' },
    icon: '💇',
    sortOrder: 3,
    isActive: true,
  },
  {
    code: 'manicure',
    name: 'Manicure',
    translations: { en: 'Manicure', fr: 'Manucure', de: 'Maniküre', it: 'Manicure', sq: 'Manikyr', es: 'Manicura' },
    description: 'Hand and nail care services',
    descriptionTranslations: { en: 'Hand and nail care services', fr: 'Soins des mains et des ongles', de: 'Hand- und Nagelpflege', it: 'Servizi di cura delle mani e delle unghie', sq: 'Shërbime për kujdesin e duarve dhe thonjve', es: 'Servicios de cuidado de manos y uñas' },
    icon: '💅',
    sortOrder: 4,
    isActive: true,
  },
  {
    code: 'pedicure',
    name: 'Pedicure',
    translations: { en: 'Pedicure', fr: 'Pédicure', de: 'Pediküre', it: 'Pedicure', sq: 'Pedikyr', es: 'Pedicura' },
    description: 'Foot and nail care services',
    descriptionTranslations: { en: 'Foot and nail care services', fr: 'Soins des pieds et des ongles', de: 'Fuß- und Nagelpflege', it: 'Servizi di cura dei piedi e delle unghie', sq: 'Shërbime për kujdesin e këmbëve dhe thonjve', es: 'Servicios de cuidado de pies y uñas' },
    icon: '🦶',
    sortOrder: 5,
    isActive: true,
  },
  {
    code: 'facial',
    name: 'Facial',
    translations: { en: 'Facial', fr: 'Soin du visage', de: 'Gesichtsbehandlung', it: 'Trattamento viso', sq: 'Trajtim fytyre', es: 'Facial' },
    description: 'Facial care and treatment services',
    descriptionTranslations: { en: 'Facial care and treatment services', fr: 'Soins et traitements du visage', de: 'Gesichtspflege und Behandlungen', it: 'Servizi di cura e trattamento del viso', sq: 'Shërbime për kujdesin dhe trajtimin e fytyrës', es: 'Servicios de cuidado y tratamiento facial' },
    icon: '🧖',
    sortOrder: 6,
    isActive: true,
  },
  {
    code: 'massage',
    name: 'Massage',
    translations: { en: 'Massage', fr: 'Massage', de: 'Massage', it: 'Massaggio', sq: 'Masazh', es: 'Masaje' },
    description: 'Therapeutic massage services',
    descriptionTranslations: { en: 'Therapeutic massage services', fr: 'Services de massage thérapeutique', de: 'Therapeutische Massage-Services', it: 'Servizi di massaggio terapeutico', sq: 'Shërbime masazhi terapeutik', es: 'Servicios de masaje terapéutico' },
    icon: '💆',
    sortOrder: 7,
    isActive: true,
  },
  {
    code: 'makeup',
    name: 'Makeup',
    translations: { en: 'Makeup', fr: 'Maquillage', de: 'Make-up', it: 'Trucco', sq: 'Grimi', es: 'Maquillaje' },
    description: 'Professional makeup services',
    descriptionTranslations: { en: 'Professional makeup services', fr: 'Services de maquillage professionnel', de: 'Professionelle Make-up-Services', it: 'Servizi di trucco professionale', sq: 'Shërbime profesionale grimi', es: 'Servicios de maquillaje profesional' },
    icon: '💄',
    sortOrder: 8,
    isActive: true,
  },
  {
    code: 'waxing',
    name: 'Waxing',
    translations: { en: 'Waxing', fr: 'Épilation', de: 'Waxing', it: 'Ceretta', sq: 'Depilim me dyllë', es: 'Depilación' },
    description: 'Hair removal waxing services',
    descriptionTranslations: { en: 'Hair removal waxing services', fr: "Services d'épilation à la cire", de: 'Haarentfernung durch Waxing', it: 'Servizi di depilazione con ceretta', sq: 'Shërbime depilimi me dyllë', es: 'Servicios de depilación con cera' },
    icon: '🪒',
    sortOrder: 9,
    isActive: true,
  },
  {
    code: 'barbering',
    name: 'Barbering',
    translations: { en: 'Barbering', fr: 'Barbier', de: 'Barbier', it: 'Barberia', sq: 'Berber', es: 'Barbería' },
    description: 'Traditional barber services',
    descriptionTranslations: { en: 'Traditional barber services', fr: 'Services de barbier traditionnels', de: 'Traditionelle Barbier-Services', it: 'Servizi da barbiere tradizionale', sq: 'Shërbime tradicionale berberi', es: 'Servicios de barbería tradicional' },
    icon: '💈',
    sortOrder: 10,
    isActive: true,
  },
  {
    code: 'other',
    name: 'Other',
    translations: { en: 'Other', fr: 'Autre', de: 'Sonstige', it: 'Altro', sq: 'Të tjera', es: 'Otro' },
    description: 'Other beauty and wellness services',
    descriptionTranslations: { en: 'Other beauty and wellness services', fr: 'Autres services de beauté et bien-être', de: 'Andere Schönheits- und Wellness-Services', it: 'Altri servizi di bellezza e benessere', sq: 'Shërbime të tjera bukurie dhe mirëqenie', es: 'Otros servicios de belleza y bienestar' },
    icon: '✨',
    sortOrder: 99,
    isActive: true,
  },
];