import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSetup1771549233491 implements MigrationInterface {
    name = 'InitialSetup1771549233491'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "t_countries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(2) NOT NULL, "name" character varying(100) NOT NULL, "lang" character varying(5) NOT NULL, "nativeName" character varying(100), "phoneCode" character varying(10), "flag" character varying(10), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dbe3c8640726362660557dff6bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_daf8e8c240f24d80bf5397ccea" ON "t_countries" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef0d156d20cafd357ebf9ce2c6" ON "t_countries" ("lang") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e3e484d35d42a2f71f8e9c801c" ON "t_countries" ("code", "lang") `);
        await queryRunner.query(`CREATE TABLE "t_cities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "countryCode" character varying(2) NOT NULL, "lang" character varying(5), "cityGroupId" uuid, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_375da346b909545b6bcfc44a1b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_05378a0970243dfed34de309c3" ON "t_cities" ("countryCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_0fa039d9b7f27706a945b274ca" ON "t_cities" ("lang") `);
        await queryRunner.query(`CREATE INDEX "IDX_6bd090532ede835ffd6b0ac52c" ON "t_cities" ("cityGroupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_29d4cfa8a5d85bc53041599bcb" ON "t_cities" ("name", "countryCode", "lang", "cityGroupId") `);
        await queryRunner.query(`CREATE TABLE "t_service_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "name" character varying(100) NOT NULL, "lang" character varying(5) NOT NULL, "description" text, "icon" character varying(50), "sortOrder" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4a1b2b906c83d72860900576c36" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3c00ac76fb5bea5552c3557867" ON "t_service_categories" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_d85bc7e31a983d5556c030f4c2" ON "t_service_categories" ("lang") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5f4e6d75bf7fadd0e6206adc91" ON "t_service_categories" ("code", "lang") `);
        await queryRunner.query(`CREATE TABLE "t_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "name" character varying(200) NOT NULL, "description" text, "categoryCode" character varying(50) NOT NULL DEFAULT 'other', "categoryLang" character varying(5) NOT NULL DEFAULT 'en', "durationMinutes" integer NOT NULL, "price" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'EUR', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_81aaedcc29b39cc2134d323c204" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4feb707b2328ba9d8f3cc9e093" ON "t_services" ("categoryCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_248af7652b0973a3a9563ee881" ON "t_services" ("categoryLang") `);
        await queryRunner.query(`CREATE INDEX "IDX_81ed3742e06c75c129df161946" ON "t_services" ("businessId", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."t_appointments_status_enum" AS ENUM('pending', 'confirmed', 'in_progress', 'completed', 'cancelled', 'no_show')`);
        await queryRunner.query(`CREATE TYPE "public"."t_appointments_source_enum" AS ENUM('ONLINE', 'USER')`);
        await queryRunner.query(`CREATE TABLE "t_appointments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "businessId" uuid NOT NULL, "employeeId" uuid NOT NULL, "serviceId" uuid NOT NULL, "startTime" TIMESTAMP NOT NULL, "endTime" TIMESTAMP NOT NULL, "status" "public"."t_appointments_status_enum" NOT NULL DEFAULT 'pending', "notes" text, "cancellationReason" text, "totalPrice" numeric(10,2), "source" "public"."t_appointments_source_enum" NOT NULL DEFAULT 'USER', "isReminderSent" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_311afc9dcc361a78bb2e68ce2be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_employee_schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employeeId" uuid NOT NULL, "dayOfWeek" integer NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "isAvailable" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b815f8fb45639f23f628bf4c0ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_employee_breaks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employeeId" uuid NOT NULL, "dayOfWeek" integer NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "title" character varying(100), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c5c1e060b0b21d3e55a7b4dc4b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_employees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "businessId" uuid NOT NULL, "bio" text, "avatar" text, "phone" character varying(20), "isActive" boolean NOT NULL DEFAULT true, "hiredAt" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aa4d122590b029017d031a26123" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_opening_hours" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "dayOfWeek" integer NOT NULL, "openTime" TIME NOT NULL, "closeTime" TIME NOT NULL, "isOpen" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_78d4409486443a9b37ba6157c40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_business_logos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" character varying NOT NULL, CONSTRAINT "PK_fd1f18a70ac049db0765ca6b1ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_businesses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(200) NOT NULL, "description" text, "ownerId" uuid NOT NULL, "cityId" uuid NOT NULL, "address" character varying(255) NOT NULL, "phone" character varying(20), "email" character varying(255), "website" character varying(255), "logoId" uuid, "images" text array NOT NULL DEFAULT '{}', "latitude" numeric(10,8), "longitude" numeric(11,8), "isActive" boolean NOT NULL DEFAULT true, "isVerified" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_caaedff430025ebd22c6b78c5c" UNIQUE ("logoId"), CONSTRAINT "PK_95c5cd60ffe87bcbe1b357b8159" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_memberships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "businessId" uuid NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "invitedAt" TIMESTAMP, "acceptedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6c71f753a0bb07ccca2a4e3a737" UNIQUE ("userId", "businessId"), CONSTRAINT "PK_d1130c595ba8fd16974f8b2dc72" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_user_roles" ("name" character varying(100) NOT NULL, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ca5f0c7219d1c99c2a3f0f4af58" PRIMARY KEY ("name"))`);
        await queryRunner.query(`CREATE TABLE "t_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying NOT NULL, "fullName" character varying NOT NULL, "userRoleId" character varying, CONSTRAINT "UQ_1b1275aba2e3044ce094936619c" UNIQUE ("email"), CONSTRAINT "PK_45e27b946b7f8cd527fd4fbe658" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_timezones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tzCode" character varying(100) NOT NULL, "name" character varying(200) NOT NULL, "lang" character varying(5) NOT NULL, "countryCode" character varying(2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_65ab7b4fe2f584dc0e22dc5b6aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_76a72840705e8312c65d60bda5" ON "t_timezones" ("tzCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_7089f082e5193b515f5f171cb0" ON "t_timezones" ("lang") `);
        await queryRunner.query(`CREATE INDEX "IDX_eed8cae1aaaf325ca2ab0a6faa" ON "t_timezones" ("countryCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a085fda92e632c0e54481404f" ON "t_timezones" ("countryCode", "lang") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9b1ba35737987dadecd9cabaf8" ON "t_timezones" ("tzCode", "lang") `);
        await queryRunner.query(`CREATE TABLE "t_employee_services" ("employeeId" uuid NOT NULL, "serviceId" uuid NOT NULL, CONSTRAINT "PK_29a16b6fbbef2b9da002804b1f3" PRIMARY KEY ("employeeId", "serviceId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_afb503ace8a39971b6220b8da7" ON "t_employee_services" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d63037efbfa803c5d71f43b7eb" ON "t_employee_services" ("serviceId") `);
        await queryRunner.query(`ALTER TABLE "t_services" ADD CONSTRAINT "FK_5fd9d3c6a97e18db6e1c30d08ed" FOREIGN KEY ("businessId") REFERENCES "t_businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_appointments" ADD CONSTRAINT "FK_8ec9fc2504f7b2dbc998e8a08d6" FOREIGN KEY ("userId") REFERENCES "t_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_appointments" ADD CONSTRAINT "FK_2cd7494cfb284ac2623e1877a66" FOREIGN KEY ("businessId") REFERENCES "t_businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_appointments" ADD CONSTRAINT "FK_980ec79bacdf347e40386e45be8" FOREIGN KEY ("employeeId") REFERENCES "t_employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_appointments" ADD CONSTRAINT "FK_603053186218b52e1586bd915c3" FOREIGN KEY ("serviceId") REFERENCES "t_services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_employee_schedules" ADD CONSTRAINT "FK_5977151bd8236e03f932da9997c" FOREIGN KEY ("employeeId") REFERENCES "t_employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_employee_breaks" ADD CONSTRAINT "FK_9e3697be6261e8e86e296635cf8" FOREIGN KEY ("employeeId") REFERENCES "t_employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_employees" ADD CONSTRAINT "FK_efacb5c3936d42e5ba224fedca5" FOREIGN KEY ("userId") REFERENCES "t_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_employees" ADD CONSTRAINT "FK_4359081417b962793c991da55c7" FOREIGN KEY ("businessId") REFERENCES "t_businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_opening_hours" ADD CONSTRAINT "FK_b332b8e12e4352c87c14477b571" FOREIGN KEY ("businessId") REFERENCES "t_businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_businesses" ADD CONSTRAINT "FK_65804f5abe53ff6144f41fe32c0" FOREIGN KEY ("ownerId") REFERENCES "t_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_businesses" ADD CONSTRAINT "FK_a19fb2fa21914bac39cc64094bc" FOREIGN KEY ("cityId") REFERENCES "t_cities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_businesses" ADD CONSTRAINT "FK_caaedff430025ebd22c6b78c5c7" FOREIGN KEY ("logoId") REFERENCES "t_business_logos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_memberships" ADD CONSTRAINT "FK_90bf8353c51357e7739486d3c42" FOREIGN KEY ("userId") REFERENCES "t_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_memberships" ADD CONSTRAINT "FK_150744c2236bb370830a8c1750f" FOREIGN KEY ("businessId") REFERENCES "t_businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_users" ADD CONSTRAINT "FK_d14bba43ef9737388222b4d1c04" FOREIGN KEY ("userRoleId") REFERENCES "t_user_roles"("name") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_employee_services" ADD CONSTRAINT "FK_afb503ace8a39971b6220b8da7a" FOREIGN KEY ("employeeId") REFERENCES "t_employees"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "t_employee_services" ADD CONSTRAINT "FK_d63037efbfa803c5d71f43b7eb7" FOREIGN KEY ("serviceId") REFERENCES "t_services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "t_employee_services" DROP CONSTRAINT "FK_d63037efbfa803c5d71f43b7eb7"`);
        await queryRunner.query(`ALTER TABLE "t_employee_services" DROP CONSTRAINT "FK_afb503ace8a39971b6220b8da7a"`);
        await queryRunner.query(`ALTER TABLE "t_users" DROP CONSTRAINT "FK_d14bba43ef9737388222b4d1c04"`);
        await queryRunner.query(`ALTER TABLE "t_memberships" DROP CONSTRAINT "FK_150744c2236bb370830a8c1750f"`);
        await queryRunner.query(`ALTER TABLE "t_memberships" DROP CONSTRAINT "FK_90bf8353c51357e7739486d3c42"`);
        await queryRunner.query(`ALTER TABLE "t_businesses" DROP CONSTRAINT "FK_caaedff430025ebd22c6b78c5c7"`);
        await queryRunner.query(`ALTER TABLE "t_businesses" DROP CONSTRAINT "FK_a19fb2fa21914bac39cc64094bc"`);
        await queryRunner.query(`ALTER TABLE "t_businesses" DROP CONSTRAINT "FK_65804f5abe53ff6144f41fe32c0"`);
        await queryRunner.query(`ALTER TABLE "t_opening_hours" DROP CONSTRAINT "FK_b332b8e12e4352c87c14477b571"`);
        await queryRunner.query(`ALTER TABLE "t_employees" DROP CONSTRAINT "FK_4359081417b962793c991da55c7"`);
        await queryRunner.query(`ALTER TABLE "t_employees" DROP CONSTRAINT "FK_efacb5c3936d42e5ba224fedca5"`);
        await queryRunner.query(`ALTER TABLE "t_employee_breaks" DROP CONSTRAINT "FK_9e3697be6261e8e86e296635cf8"`);
        await queryRunner.query(`ALTER TABLE "t_employee_schedules" DROP CONSTRAINT "FK_5977151bd8236e03f932da9997c"`);
        await queryRunner.query(`ALTER TABLE "t_appointments" DROP CONSTRAINT "FK_603053186218b52e1586bd915c3"`);
        await queryRunner.query(`ALTER TABLE "t_appointments" DROP CONSTRAINT "FK_980ec79bacdf347e40386e45be8"`);
        await queryRunner.query(`ALTER TABLE "t_appointments" DROP CONSTRAINT "FK_2cd7494cfb284ac2623e1877a66"`);
        await queryRunner.query(`ALTER TABLE "t_appointments" DROP CONSTRAINT "FK_8ec9fc2504f7b2dbc998e8a08d6"`);
        await queryRunner.query(`ALTER TABLE "t_services" DROP CONSTRAINT "FK_5fd9d3c6a97e18db6e1c30d08ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d63037efbfa803c5d71f43b7eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_afb503ace8a39971b6220b8da7"`);
        await queryRunner.query(`DROP TABLE "t_employee_services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b1ba35737987dadecd9cabaf8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a085fda92e632c0e54481404f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eed8cae1aaaf325ca2ab0a6faa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7089f082e5193b515f5f171cb0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76a72840705e8312c65d60bda5"`);
        await queryRunner.query(`DROP TABLE "t_timezones"`);
        await queryRunner.query(`DROP TABLE "t_users"`);
        await queryRunner.query(`DROP TABLE "t_user_roles"`);
        await queryRunner.query(`DROP TABLE "t_memberships"`);
        await queryRunner.query(`DROP TABLE "t_businesses"`);
        await queryRunner.query(`DROP TABLE "t_business_logos"`);
        await queryRunner.query(`DROP TABLE "t_opening_hours"`);
        await queryRunner.query(`DROP TABLE "t_employees"`);
        await queryRunner.query(`DROP TABLE "t_employee_breaks"`);
        await queryRunner.query(`DROP TABLE "t_employee_schedules"`);
        await queryRunner.query(`DROP TABLE "t_appointments"`);
        await queryRunner.query(`DROP TYPE "public"."t_appointments_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."t_appointments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81ed3742e06c75c129df161946"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_248af7652b0973a3a9563ee881"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4feb707b2328ba9d8f3cc9e093"`);
        await queryRunner.query(`DROP TABLE "t_services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f4e6d75bf7fadd0e6206adc91"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d85bc7e31a983d5556c030f4c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c00ac76fb5bea5552c3557867"`);
        await queryRunner.query(`DROP TABLE "t_service_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29d4cfa8a5d85bc53041599bcb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bd090532ede835ffd6b0ac52c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0fa039d9b7f27706a945b274ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05378a0970243dfed34de309c3"`);
        await queryRunner.query(`DROP TABLE "t_cities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3e484d35d42a2f71f8e9c801c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef0d156d20cafd357ebf9ce2c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_daf8e8c240f24d80bf5397ccea"`);
        await queryRunner.query(`DROP TABLE "t_countries"`);
    }

}
